spring:
  application:
    name: tool
  datasource:
    url: "jdbc:mysql://localhost:3306/attendance_tool"
    username: root
    password: 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

